import { Router } from "express";
import { authRouter } from "../modules/auth/auth.routes";
import { menuRouter } from "../modules/menu/menu.routes";
import { recipesRouter } from "../modules/recipes/recipes.routes";
import { inventoryRouter } from "../modules/inventory/inventory.routes";
import { suppliersRouter } from "../modules/suppliers/suppliers.routes";
import { purchasesRouter } from "../modules/purchases/purchases.routes";
import { ordersRouter } from "../modules/orders/orders.routes";
import { kitchenRouter } from "../modules/kitchen/kitchen.routes";
import { expensesRouter } from "../modules/expenses/expenses.routes";
import { cashRouter } from "../modules/cash/cash.routes";
import { bankRouter } from "../modules/bank/bank.routes";
import { paymentMethodsRouter } from "../modules/paymentMethods/paymentMethods.routes";
import { staffRouter } from "../modules/staff/staff.routes";
import { dailyClosingRouter } from "../modules/dailyClosing/dailyClosing.routes";
import { dashboardRouter } from "../modules/dashboard/dashboard.routes";
import { reportsRouter } from "../modules/reports/reports.routes";
import { auditRouter } from "../modules/audit/audit.routes";
import { settingsRouter } from "../modules/settings/settings.routes";
import { backupRouter } from "../modules/backup/backup.routes";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/menu", menuRouter);
apiRouter.use("/recipes", recipesRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/suppliers", suppliersRouter);
apiRouter.use("/purchases", purchasesRouter);
apiRouter.use("/orders", ordersRouter);
apiRouter.use("/kitchen", kitchenRouter);
apiRouter.use("/expenses", expensesRouter);
apiRouter.use("/cash", cashRouter);
apiRouter.use("/bank", bankRouter);
apiRouter.use("/payment-methods", paymentMethodsRouter);
apiRouter.use("/staff", staffRouter);
apiRouter.use("/daily-closing", dailyClosingRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/audit-logs", auditRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/backup", backupRouter);
